import { ALL_HEALTH_COVERAGE_MODULES } from "@insurance-advisor/domain";
import type { Question } from "./question.js";

/**
 * Starter questionnaire — PRD §49. ONE unified question bank across all
 * five calculators (life, disability, critical illness, LTC, health
 * modules), not five separate silos — matching the PRD's own design
 * (§7/§10: one adaptive questionnaire produces Facts that every
 * calculator draws from). A household answers "how many dependents do
 * you have" once, not five times.
 *
 * Fact keys follow the dotted convention from PRD §8's own examples —
 * the canonical Facts layer naming, distinct from any one calculator's
 * input field names. `packages/calculators/src/facts-to-*-input.ts`
 * bridge Facts → each calculator's input shape (see docs/DECISIONS.md).
 *
 * A few PRD concepts are deliberately conflated onto one fact here rather
 * than asked twice — see docs/ASSUMPTIONS.md:
 * - "survivor reliable income" (life, §12.3) and "reliable income during
 *   disability" (§13.1) share `income.survivor.reliableMonthly` — in
 *   practice usually the same figure (a spouse's own continuing salary).
 * - "household required annual spend" (life) and "essential monthly
 *   expenses" (disability/CI) share `expenses.household.monthly` — the
 *   PRD's own §13.1 formula subsets to "essential" while life's §12.3
 *   uses total spend; asking one number and using it for both slightly
 *   overstates the disability/CI need rather than understating it.
 */
export const STARTER_QUESTIONS: Question[] = [
  {
    id: "household_marital_status",
    version: 1,
    category: "household",
    text: "מה המצב המשפחתי שלך?",
    answerType: "single_select",
    required: true,
    factsProduced: ["household.maritalStatus"],
    // Highest decisionImpact in the bank: this frames almost everything that
    // follows (is there a spouse whose income/continuation matters at all?),
    // so it should be the very first question asked, not a late one. Raised
    // from 0.2 after direct user feedback that it was scored too low.
    decisionImpact: 0.95,
  },
  {
    id: "household_dependents_count",
    version: 1,
    category: "household",
    text: "כמה ילדים או תלויים כלכליים יש במשפחה?",
    answerType: "number",
    required: true,
    validation: [{ kind: "range", params: { min: 0, max: 15 }, severity: "warning", message: "מספר תלויים גבוה מהרגיל — נכון?" }],
    factsProduced: ["household.dependents.count"],
    decisionImpact: 0.9,
  },
  {
    id: "household_youngest_dependent_age",
    version: 1,
    category: "household",
    text: "מה גיל הילד/ה הצעיר/ה?",
    answerType: "number",
    required: false,
    requiredWhen: { questionId: "household_dependents_count", operator: ">", value: 0 },
    showWhen: { questionId: "household_dependents_count", operator: ">", value: 0 },
    validation: [{ kind: "range", params: { min: 0, max: 25 }, severity: "warning", message: "גיל חריג — נכון?" }],
    factsProduced: ["household.youngestDependentAge"],
    decisionImpact: 0.8,
  },
  {
    id: "household_dependents_monthly_needs",
    version: 1,
    category: "expenses",
    text: "כמה עולה בחודש לכלכל את הילדים/התלויים (חינוך, חוגים, טיפול וכו')?",
    helpText: "מעבר להוצאות הבית הכלליות שכבר ציינת — הסכום הספציפי לתלויים, נדרש לחישוב ביטוח אבדן כושר עבודה (PRD §13.1).",
    answerType: "money",
    required: false,
    showWhen: { questionId: "household_dependents_count", operator: ">", value: 0 },
    requiredWhen: { questionId: "household_dependents_count", operator: ">", value: 0 },
    validation: [{ kind: "range", params: { min: 0, max: 100_000 }, severity: "warning", message: "סכום גבוה מהרגיל — נכון?" }],
    normalizer: "roundMoneyToShekel",
    factsProduced: ["expenses.dependents.monthly"],
    decisionImpact: 0.6,
  },
  {
    id: "person_current_age",
    version: 1,
    category: "personal",
    text: "מה הגיל שלך?",
    answerType: "number",
    required: true,
    validation: [{ kind: "range", params: { min: 18, max: 100 }, severity: "warning", message: "גיל חריג — נכון?" }],
    factsProduced: ["person.currentAge"],
    decisionImpact: 0.4,
  },
  {
    id: "person_retirement_age",
    version: 1,
    category: "personal",
    text: "באיזה גיל אתה מתכנן לפרוש?",
    helpText: "לרוב 67 — אפשר להשאיר ריק ולתת למערכת להניח ברירת מחדל.",
    answerType: "number",
    required: false,
    validation: [{ kind: "range", params: { min: 50, max: 80 }, severity: "warning", message: "גיל פרישה חריג — נכון?" }],
    factsProduced: ["person.retirementAge"],
    decisionImpact: 0.3,
  },
  {
    id: "expenses_household_monthly",
    version: 1,
    category: "expenses",
    text: "מהן ההוצאות החודשיות הכוללות של משק הבית?",
    helpText: "כולל דיור, מזון, חינוך, ותשלומי חובות — הסכום שהמשפחה צריכה כדי לשמור על רמת החיים הנוכחית.",
    answerType: "money",
    required: true,
    validation: [{ kind: "range", params: { min: 0, max: 500_000 }, severity: "warning", message: "סכום גבוה מהרגיל — נכון?" }],
    normalizer: "roundMoneyToShekel",
    factsProduced: ["expenses.household.monthly"],
    decisionImpact: 0.9,
  },
  {
    id: "income_survivor_reliable_monthly",
    version: 1,
    category: "income",
    text: "כמה הכנסה חודשית אמינה תישאר למשפחה במקרה פטירה או אבדן כושר עבודה שלך? (למשל הכנסת בן/בת הזוג)",
    answerType: "money",
    required: true,
    normalizer: "roundMoneyToShekel",
    factsProduced: ["income.survivor.reliableMonthly"],
    decisionImpact: 0.85,
  },
  {
    id: "debt_mortgage_exists",
    version: 1,
    category: "debts",
    text: "האם יש לך משכנתה?",
    answerType: "boolean",
    required: true,
    factsProduced: ["debt.mortgage.exists"],
    decisionImpact: 0.5,
  },
  {
    id: "debt_mortgage_balance",
    version: 1,
    category: "debts",
    text: "מה יתרת המשכנתה הנוכחית?",
    answerType: "money",
    required: false,
    showWhen: { questionId: "debt_mortgage_exists", operator: "==", value: true },
    requiredWhen: { questionId: "debt_mortgage_exists", operator: "==", value: true },
    validation: [{ kind: "range", params: { min: 0, max: 20_000_000 }, severity: "warning", message: "יתרת משכנתה חריגה — נכון?" }],
    normalizer: "roundMoneyToShekel",
    factsProduced: ["debt.mortgage.balance"],
    decisionImpact: 0.7,
  },
  {
    id: "debt_mortgage_monthly_payment",
    version: 1,
    category: "debts",
    text: "מה התשלום החודשי על המשכנתה?",
    answerType: "money",
    required: false,
    showWhen: { questionId: "debt_mortgage_exists", operator: "==", value: true },
    normalizer: "roundMoneyToShekel",
    factsProduced: ["debt.mortgage.monthlyPayment"],
    decisionImpact: 0.5,
  },
  {
    id: "debt_mortgage_has_lender_insurance",
    version: 1,
    category: "debts",
    text: "האם יש ביטוח חיים למשכנתה עם הבנק/הגוף המלווה כמוטב?",
    answerType: "boolean",
    required: false,
    showWhen: { questionId: "debt_mortgage_exists", operator: "==", value: true },
    factsProduced: ["debt.mortgage.hasLenderBeneficiaryCoverage"],
    decisionImpact: 0.4,
  },
  {
    id: "debt_mortgage_lender_coverage_amount",
    version: 1,
    category: "debts",
    text: "מה סכום הכיסוי של ביטוח המשכנתה?",
    answerType: "money",
    required: false,
    showWhen: { questionId: "debt_mortgage_has_lender_insurance", operator: "==", value: true },
    normalizer: "roundMoneyToShekel",
    factsProduced: ["debt.mortgage.lenderBeneficiaryCoverageAmount"],
    decisionImpact: 0.3,
  },
  {
    id: "coverage_life_existing_amount",
    version: 1,
    category: "existing_coverage",
    text: "מה סכום ביטוח החיים הקיים שלך (לא כולל ביטוח משכנתה)?",
    helpText: "ביטוח חיים שהמוטב בו הוא בן/בת הזוג או המשפחה — לא ביטוח משכנתה שהמוטב בו הוא הבנק.",
    answerType: "money",
    required: true,
    normalizer: "roundMoneyToShekel",
    factsProduced: ["coverage.life.existingAmount"],
    decisionImpact: 0.6,
  },
  {
    id: "coverage_disability_existing_monthly",
    version: 1,
    category: "existing_coverage",
    text: "מה סכום הכיסוי החודשי הקיים שלך לאבדן כושר עבודה (נטו, אם ידוע)?",
    helpText: "כולל ביטוח דרך הפנסיה, ביטוח פרטי, וכיסוי מעסיק יחד.",
    answerType: "money",
    required: true,
    normalizer: "roundMoneyToShekel",
    factsProduced: ["coverage.disability.existingNetMonthly"],
    decisionImpact: 0.6,
  },
  {
    id: "coverage_critical_illness_existing_amount",
    version: 1,
    category: "existing_coverage",
    text: "מה סכום ביטוח מחלות קשות הקיים שלך?",
    answerType: "money",
    required: true,
    normalizer: "roundMoneyToShekel",
    factsProduced: ["coverage.criticalIllness.existingAmount"],
    decisionImpact: 0.5,
  },
  {
    id: "coverage_ltc_existing_monthly_benefit",
    version: 1,
    category: "existing_coverage",
    text: "האם יש לך ביטוח סיעודי קיים? אם כן, מה גובה הקצבה החודשית?",
    answerType: "money",
    required: false,
    normalizer: "roundMoneyToShekel",
    factsProduced: ["coverage.ltc.existingMonthlyBenefit"],
    decisionImpact: 0.3,
  },
  {
    id: "assets_earmarked_liquid",
    version: 1,
    category: "assets",
    text: "כמה נכסים נזילים (מזומן/פיקדונות) תייעד המשפחה להתמודדות עם אובדן הכנסה?",
    answerType: "money",
    required: true,
    normalizer: "roundMoneyToShekel",
    factsProduced: ["assets.earmarkedLiquid"],
    decisionImpact: 0.5,
  },
  {
    id: "assets_monthly_self_funding_capacity",
    version: 1,
    category: "assets",
    text: "כמה יכולה המשפחה לממן מדי חודש באופן עצמאי לצורך סיעודי, אם יידרש?",
    answerType: "money",
    required: false,
    normalizer: "roundMoneyToShekel",
    factsProduced: ["assets.monthlySelfFundingCapacity"],
    decisionImpact: 0.3,
  },
  {
    id: "goals_education_amount",
    version: 1,
    category: "goals",
    text: "האם יש רזרבה שתרצה לייעד לחינוך הילדים? אם כן, כמה?",
    answerType: "money",
    required: false,
    showWhen: { questionId: "household_dependents_count", operator: ">", value: 0 },
    normalizer: "roundMoneyToShekel",
    factsProduced: ["goals.education.amount"],
    decisionImpact: 0.3,
  },
  {
    id: "budget_monthly_protection",
    version: 1,
    category: "goals",
    text: "כמה אתה מרגיש בנוח להקצות בחודש עבור ביטוחי הגנה (חיים/אבדן כושר עבודה וכו')?",
    helpText: "זה לא מקטין את הצורך המחושב — זה רק מוסיף אפשרות נוספת מוגבלת-תקציב לצדו (PRD §20).",
    answerType: "money",
    required: false,
    normalizer: "roundMoneyToShekel",
    factsProduced: ["budget.monthlyProtectionBudget"],
    decisionImpact: 0.4,
  },
  {
    id: "person_protection_horizon_override",
    version: 1,
    category: "personal",
    text: "האם תרצה לקבוע בעצמך תקופת הגנה (בשנים) במקום החישוב האוטומטי?",
    helpText: "לרוב עדיף להשאיר ריק ולתת למערכת לחשב לפי גיל הילדים/המשכנתה.",
    answerType: "number",
    required: false,
    factsProduced: ["person.protectionHorizonOverrideYears"],
    decisionImpact: 0.1,
  },
  // One single_select question per PRD §15 health module, generated rather
  // than hand-duplicated 7 times. Answer values are "yes" | "no" | "unknown".
  ...ALL_HEALTH_COVERAGE_MODULES.map(
    (module): Question => ({
      id: `health_module_${module}`,
      version: 1,
      category: "health",
      text: `האם יש לך כיסוי ביטוחי פרטי עבור: ${module}?`,
      answerType: "single_select",
      required: false,
      factsProduced: [`health.module.${module}`],
      decisionImpact: 0.2,
    }),
  ),
];
