import type { Question } from "./question.js";

/**
 * Starter questionnaire — PRD §49, scoped to the Life Insurance
 * calculator only for this pass (not disability/CI/health/LTC yet, which
 * the PRD's Third Prompt also asks for — see docs/DECISIONS.md for why
 * this is split into a smaller, real, working slice instead of a wider
 * but shallower one).
 *
 * Fact keys follow the dotted convention from PRD §8's own examples
 * (`person.age`, `household.dependents.count`, ...) — this is the
 * canonical Facts layer naming, distinct from `LifeCalculatorInput`'s
 * field names. `packages/calculators/src/facts-to-life-input.ts` bridges
 * the two — the real Facts→calculator-input adapter this questionnaire
 * makes possible, replacing the `fromHouseholdFixture` demo adapter for
 * anyone going through this flow instead of a hardcoded fixture.
 */
export const STARTER_LIFE_QUESTIONS: Question[] = [
  {
    id: "household_marital_status",
    version: 1,
    category: "household",
    text: "מה המצב המשפחתי שלך?",
    answerType: "single_select",
    required: true,
    factsProduced: ["household.maritalStatus"],
    decisionImpact: 0.2,
  },
  {
    id: "household_dependents_count",
    version: 1,
    category: "household",
    text: "כמה ילדים או תלויים כלכליים יש במשפחה?",
    answerType: "number",
    required: true,
    validation: [{ kind: "range", params: { min: 0, max: 15 }, severity: "warning", message: "מספר תלויים גבוה מהרגיל — נכון?" }],
    factsProduced: ["household.dependents.count"],
    decisionImpact: 0.9,
  },
  {
    id: "household_youngest_dependent_age",
    version: 1,
    category: "household",
    text: "מה גיל הילד/ה הצעיר/ה?",
    answerType: "number",
    required: false,
    requiredWhen: { questionId: "household_dependents_count", operator: ">", value: 0 },
    showWhen: { questionId: "household_dependents_count", operator: ">", value: 0 },
    validation: [{ kind: "range", params: { min: 0, max: 25 }, severity: "warning", message: "גיל חריג — נכון?" }],
    factsProduced: ["household.youngestDependentAge"],
    decisionImpact: 0.8,
  },
  {
    id: "expenses_household_monthly",
    version: 1,
    category: "expenses",
    text: "מהן ההוצאות החודשיות הכוללות של משק הבית?",
    helpText: "כולל דיור, מזון, חינוך, ותשלומי חובות — הסכום שהמשפחה צריכה כדי לשמור על רמת החיים הנוכחית.",
    answerType: "money",
    required: true,
    validation: [{ kind: "range", params: { min: 0, max: 500_000 }, severity: "warning", message: "סכום גבוה מהרגיל — נכון?" }],
    normalizer: "roundMoneyToShekel",
    factsProduced: ["expenses.household.monthly"],
    decisionImpact: 0.9,
  },
  {
    id: "income_survivor_reliable_monthly",
    version: 1,
    category: "income",
    text: "כמה הכנסה חודשית אמינה תישאר למשפחה במקרה פטירה שלך? (למשל הכנסת בן/בת הזוג)",
    answerType: "money",
    required: true,
    normalizer: "roundMoneyToShekel",
    factsProduced: ["income.survivor.reliableMonthly"],
    decisionImpact: 0.85,
  },
  {
    id: "debt_mortgage_exists",
    version: 1,
    category: "debts",
    text: "האם יש לך משכנתה?",
    answerType: "boolean",
    required: true,
    factsProduced: ["debt.mortgage.exists"],
    decisionImpact: 0.5,
  },
  {
    id: "debt_mortgage_balance",
    version: 1,
    category: "debts",
    text: "מה יתרת המשכנתה הנוכחית?",
    answerType: "money",
    required: false,
    showWhen: { questionId: "debt_mortgage_exists", operator: "==", value: true },
    requiredWhen: { questionId: "debt_mortgage_exists", operator: "==", value: true },
    validation: [{ kind: "range", params: { min: 0, max: 20_000_000 }, severity: "warning", message: "יתרת משכנתה חריגה — נכון?" }],
    normalizer: "roundMoneyToShekel",
    factsProduced: ["debt.mortgage.balance"],
    decisionImpact: 0.7,
  },
  {
    id: "debt_mortgage_has_lender_insurance",
    version: 1,
    category: "debts",
    text: "האם יש ביטוח חיים למשכנתה עם הבנק/הגוף המלווה כמוטב?",
    answerType: "boolean",
    required: false,
    showWhen: { questionId: "debt_mortgage_exists", operator: "==", value: true },
    factsProduced: ["debt.mortgage.hasLenderBeneficiaryCoverage"],
    decisionImpact: 0.4,
  },
  {
    id: "debt_mortgage_lender_coverage_amount",
    version: 1,
    category: "debts",
    text: "מה סכום הכיסוי של ביטוח המשכנתה?",
    answerType: "money",
    required: false,
    showWhen: { questionId: "debt_mortgage_has_lender_insurance", operator: "==", value: true },
    normalizer: "roundMoneyToShekel",
    factsProduced: ["debt.mortgage.lenderBeneficiaryCoverageAmount"],
    decisionImpact: 0.3,
  },
  {
    id: "coverage_life_existing_amount",
    version: 1,
    category: "existing_coverage",
    text: "מה סכום ביטוח החיים הקיים שלך (לא כולל ביטוח משכנתה)?",
    helpText: "ביטוח חיים שהמוטב בו הוא בן/בת הזוג או המשפחה — לא ביטוח משכנתה שהמוטב בו הוא הבנק.",
    answerType: "money",
    required: true,
    normalizer: "roundMoneyToShekel",
    factsProduced: ["coverage.life.existingAmount"],
    decisionImpact: 0.6,
  },
  {
    id: "assets_earmarked_liquid",
    version: 1,
    category: "assets",
    text: "כמה נכסים נזילים (מזומן/פיקדונות) תייעד המשפחה להתמודדות עם אובדן הכנסה?",
    answerType: "money",
    required: true,
    normalizer: "roundMoneyToShekel",
    factsProduced: ["assets.earmarkedLiquid"],
    decisionImpact: 0.5,
  },
  {
    id: "goals_education_amount",
    version: 1,
    category: "goals",
    text: "האם יש רזרבה שתרצה לייעד לחינוך הילדים? אם כן, כמה?",
    answerType: "money",
    required: false,
    showWhen: { questionId: "household_dependents_count", operator: ">", value: 0 },
    normalizer: "roundMoneyToShekel",
    factsProduced: ["goals.education.amount"],
    decisionImpact: 0.3,
  },
  {
    id: "person_protection_horizon_override",
    version: 1,
    category: "personal",
    text: "האם תרצה לקבוע בעצמך תקופת הגנה (בשנים) במקום החישוב האוטומטי?",
    helpText: "לרוב עדיף להשאיר ריק ולתת למערכת לחשב לפי גיל הילדים/המשכנתה.",
    answerType: "number",
    required: false,
    factsProduced: ["person.protectionHorizonOverrideYears"],
    decisionImpact: 0.1,
  },
];
